# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 API Cloud Documentation
site_description: Documentation for WSO2 API Cloud
site_author: WSO2
site_url: https://wso2.com/api-cloud/

# Repository
repo_name: wso2/docs-cloud
repo_url: https://github.com/wso2/docs-cloud
edit_uri: https://github.com/wso2/docs-cloud/edit/master/en/docs/

# Copyright
copyright: WSO2 API Cloud - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'
  
# Navigation
nav:
  - 'Welcome to the WSO2 API Cloud Documentation': index.md
  - 'Get Started':
     - 'Overview': get-started/overview.md
     - 'Key Concepts': get-started/key-concepts.md
     - 'Quick Start Guide': get-started/quick-start-guide.md
     - 'Tutorials':
        - 'Create and Publish an API': get-started/tutorials/create-and-publish-an-api.md
        - 'Subscribe to and Invoke an API ': get-started/tutorials/subscribe-to-and-invoke-an-api.md
        - 'Expose your On-Premises Backend Services to WSO2 API Cloud': get-started/tutorials/expose-your-backend-services-to-api-cloud.md
        - 'Enforce Throttling and Resource Access Policies': get-started/tutorials/enforce-throttling-and-resource-access-policies.md
  - 'Learn':
     - 'Design APIs':
        - 'Design a New REST API': learn/design-apis/design-a-new-rest-api.md
        - 'Design a New WebSocket API': learn/design-apis/design-a-websocket-api.md
        - 'Design an API Using Existing Swagger Definition': learn/design-apis/design-an-api-using-existing-swagger.md
     - 'Secure APIs':
        - 'Secure APIs using OAuth2 Access Tokens': learn/secure-apis/secure-apis-using-oauth2-access-tokens.md
     - 'Publish APIs':
        - 'Publish an API': learn/publish-apis/publish-an-api.md
     - 'Manage APIs':
        - 'API Lifecycle Management Overview': learn/manage-apis/api-lifecycle-management-overview.md
        - 'Manage API Lifecycle': learn/manage-apis/manage-api-lifecycle.md
        - 'Create a New API Version': learn/manage-apis/create-a-new-api-version.md
        - 'Deprecate an Old API Version': learn/manage-apis/deprecate-an-old-api-version.md
     - 'Consume APIs':
        - 'Discover APIs': learn/consume-apis/discover-apis.md
        - 'Manage Applications':
           - 'Create Applications': learn/consume-apis/create-applications.md
           - 'Generate Application Keys': learn/consume-apis/work-with-api-keys.md
           - 'Work with Access Tokens':
              - 'Overview of Access Tokens': learn/consume-apis/overview-of-access-tokens.md
              - 'Access Tokens Per Device': learn/consume-apis/access-tokens-per-device.md
           - 'Share Applications': learn/consume-api/manage-application/sharing-applications/sharing-applications.md
           - 'Add Custom Attributes to Applications': learn/consume-api/manage-application/advanced-topics/add-custom-attributes-to-applications.md
           - 'Change the Owner of an Application': learn/consume-api/manage-application/advanced-topics/changing-the-owner-of-an-application.md
        - 'Manage Subscriptions':
           - 'Subscribe to an API': learn/consume-api/manage-subscription/subscribe-to-an-api.md
           - 'Invoke an APIs':
              - 'Invoke an API Using the Integrated API Console': learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-the-integrated-api-console.md
              - 'Invoke an API Using a SOAP Client': learn/consume-api/invoke-apis/invoke-apis-using-tools/invoke-an-api-using-a-soap-client.md
           - 'Use the Community Features': learn/consume-api/collaboration/use-the-community-features.md
           - 'Generate SDKs':
              - 'Generate SDKs in Developer Portal': learn/consume-api/generating-sdks/generate-sdks-in-dev-portal.md
              - 'Write a Client Application Using the SDK': learn/consume-api/generating-sdks/write-a-client-application-using-the-sdk.md
     - 'Control API Traffic':
        - 'Throttling and Rate Limiting Overview': learn/control-api-traffic/throttling-and-rate-limiting-overview.md
        - 'Apply Throttling Policies':
           - 'Advanced Throttling Policies': learn/control-api-traffic/advanced-throttling-policies.md
           - 'Application Throttling Policies': learn/control-api-traffic/application-throttling-policies.md
           - 'Blacklist Policies': learn/control-api-traffic/blacklist-policies.md
     - 'Analyze APIs':
        - 'API Analytics Overview': learn/analyze-apis/api-analytics-overview.md
  - 'Administer':
     - 'Add New Organization': administer/add-new-organization.md
     - 'Change Organization Name': administer/change-organization-name.md
     - 'Add Members to Your Organization': administer/add-members-to-your-organization.md
     - 'Register and Invite Members': administer/register-and-invite-members.md
     - 'View and Download Logs': administer/view-and-download-logs.md
     - 'Migrate APIs and Applications Between Environments': administer/migrate-using-cli-tool.md
  - 'Customize':
     - 'Customize Your Portal':
        - 'Customize the API Store Theme': customize/customize-the-api-store-theme.md
        - 'Customize Cloud Domains':
           - 'Configure Custom Cloud Domains': customize/customize-cloud-domains.md
           - 'Generate SSL Certificates and DNS Records': customize/generate-ssl-certs-and-dns-records.md
           - 'Customize the API Store Domain': customize/customize-api-store-domain.md
           - 'Customize the API Publisher Domain': customize/customize-api-publisher-domain.md
           - 'Customize the Admin Portal Domain': customize/customize-admin-portal-domain.md
           - 'Customize Gateway Domain': customize/customize-gateway-domain.md
        - 'Customize Invitation Emails': customize/customize-invitation-emails.md
  - 'Hybrid API Management':
     - 'Overview': hybrid-api-management/overview.md
     - 'Deploy the Microgateway': hybrid-api-management/deploy-the-microgateway.md 
     - 'Deploy the Microgateway as a Docker Container': hybrid-api-management/deploy-microgateway-as-docker-container.md
     - 'Deploy the Microgateway on a Kubernetes Cluster': hybrid-api-management/deploy-microgateway-on-kubernetes-cluster.md
     - 'Deploy Grouped APIs Using a Microgateway': hybrid-api-management/deploy-grouped-apis-using-a-microgateway.md
  - 'Management APIs':
     - 'Overview of Management APIs': management-apis/overview.md
     - 'Common Cloud APIs': management-apis/common-cloud-apis.md
     - 'RESTful APIs':
        - 'Publisher APIs':
           - 'Get Started with Publisher APIs': management-apis/publisher-get-started.md
           - 'Try Out Publisher APIs': management-apis/publisher-v1.md
        - 'Store APIs':
           - 'Get Started with Store APIs': management-apis/devportal-get-started.md
           - 'Try Out Store APIs': management-apis/devportal-v1.md
        - 'Admin APIs':
           - 'Get Started with Admin APIs': management-apis/admin-get-started.md
           - 'Try Out Admin APIs': management-apis/admin-v1.md
        - 'Analytics APIs':
           - 'Get Started with Analytics APIs': management-apis/analytics-get-started.md
           - 'Try Out Analytics APIs': management-apis/analytics.md
     - 'Subscriber Management APIs': management-apis/subscriber-management-apis.md
     - 'Token API': 
        - 'Overview of Token API': management-apis/token-api.md
        - 'Authorization Code Grant': management-apis/grant-types/authorization-code-grant.md
        - 'Client Credentials Grant': management-apis/grant-types/client-credentials-grant.md
        - 'Password Grant': management-apis/grant-types/password-grant.md
        - 'Refresh Token Grant': management-apis/grant-types/refresh-token-grant.md
        - 'SAML Extension Grant': management-apis/grant-types/saml-extension-grant.md
  - 'FAQ Library':
     - 'API Creation and Design': faq-library/api-creation-and-design.md
     - 'API Subscription Tiers': faq-library/api-subscription-tiers.md
     - 'API Search': faq-library/api-search.md
     - 'API Deletion': faq-library/api-deletion.md
     - 'API Backend and Endpoint Security': faq-library/api-backends-and-endpoint-security.md
     - 'VPN Connection with API Cloud': faq-library/vpn-with-api-cloud.md
     - 'Request/Response Transformation': faq-library/request-response-transformation.md
     - 'Microgateway': faq-library/microgateway.md
     - 'API Cloud Gateway': faq-library/api-cloud-gateway.md   
  - 'Get Support':
     - 'Work with the Support Team ': get-support/work-with-the-support-team.md
  - '': page-not-found.md 
  

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
    
# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
